### PR TITLE
PR for Native Pipes

### LINKED ISSUE #25: wishlist: accessibility resources?
Around the intro to viridis, or else just in the resources section, it'd be really wonderful to include some reference or resources to accessible design principles (e.g. text size, color/contrast, alternative text for figures) would be amazing! If this is of interest, I'd be happy to pull a couple resources or write a sentence or two into the existing instructor script.

### PR DESCRIPTION
**Pull request by asteves**
This PR replaces `magrittr` based pipes `%>%` with R's new native pipe `|>`. No functionality is affected by this change other than pipe replacement. 

The PR also closes #25 

- Adds multiple accessibility design resources to the resource list.

### CODE REVIEW

**Comment by pssachdeva** [comment]
Will the new pipe only work if someone has updated to the most recent version of R?

**Comment by asteves** [comment]
Yes, they have to be on R 4.1 or higher for the native pipe to work.

**Comment by pssachdeva** [comment]
I am not sure how fast adoption of newer R versions happens. Should we hold off on these merges to give people time to update their R versions?

**Comment by asteves** [comment]
I think we can certainly hold off for this one for next week. Most people practically probably don't update their R on their own. The place where I think this adoption can happen now is R-Fundamentals because people are just starting for the first time. 

I would think that these merges should come before next year, maybe before the summer?

**Pull request merged**
